In [10]:
import pandas as pd

dados = {'Vendedor' : ['Naruto', 'Goku', 'Seiya'],
        'Produto' : ['Geladeira', 'Fogão', 'Ar Condicionado'],
        'Valor Vendido' : [3400, 750, 2650]}

df = pd.DataFrame(dados)
df

#display = apresenta em forma de planilha / para display não é necessário digitar display

  Vendedor          Produto  Valor Vendido
0   Naruto        Geladeira           3400
1     Goku            Fogão            750
2    Seiya  Ar Condicionado           2650

In [11]:
import pandas as pd
import numpy as np

In [12]:
dados = 'https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv'

df = pd.read_csv(dados, encoding="latin1", sep= ';')

In [13]:
#dados = 'BaseDPEvolucaoMensalCisp.csv'

#df = pd.read_csv(dados, encoding="latin1", sep= ';')

#df.head(3)

In [14]:
df.tail(3)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
37585,166,3,2026,2026m03,33,5,Angra dos Reis,3300100,Interior,2,...,14.0,1.0,91,10,0,0,0,0,744,2
37586,167,3,2026,2026m03,43,5,Paraty,3303807,Interior,0,...,7.0,0.0,25,1,0,0,0,0,259,2
37587,168,3,2026,2026m03,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,8,0,0,0,0,0,52,2

In [15]:
df.columns

Index(['cisp', 'mes', 'ano', 'mes_ano', 'aisp', 'risp', 'munic', 'mcirc',
       'regiao', 'hom_doloso', 'lesao_corp_morte', 'latrocinio', 'cvli',
       'hom_por_interv_policial', 'feminicidio', 'letalidade_violenta',
       'tentat_hom', 'tentativa_feminicidio', 'lesao_corp_dolosa', 'estupro',
       'hom_culposo', 'lesao_corp_culposa', 'roubo_transeunte',
       'roubo_celular', 'roubo_em_coletivo', 'roubo_rua', 'roubo_veiculo',
       'roubo_carga', 'roubo_comercio', 'roubo_residencia', 'roubo_banco',
       'roubo_cx_eletronico', 'roubo_conducao_saque', 'roubo_apos_saque',
       'roubo_bicicleta', 'outros_roubos', 'total_roubos', 'furto_veiculos',
       'furto_transeunte', 'furto_coletivo', 'furto_celular',
       'furto_bicicleta', 'outros_furtos', 'total_furtos', 'sequestro',
       'extorsao', 'sequestro_relampago', 'estelionato', 'apreensao_drogas',
       'posse_drogas', 'trafico_drogas', 'apreensao_drogas_sem_autor',
       'recuperacao_veiculos', 'apf', 'aaapai', 'cmp', 'cmba', 'ameaca',
       'pessoas_desaparecidas', 'encontro_cadaver', 'encontro_ossada',
       'pol_militares_mortos_serv', 'pol_civis_mortos_serv',
       'registro_ocorrencias', 'fase'],
      dtype='str')

In [16]:
df.shape #indica o número de linhas e colunas

(37588, 65)

In [17]:
df.dtypes #indica

cisp                         int64
mes                          int64
ano                          int64
mes_ano                        str
aisp                         int64
                             ...
encontro_ossada              int64
pol_militares_mortos_serv    int64
pol_civis_mortos_serv        int64
registro_ocorrencias         int64
fase                         int64
Length: 65, dtype: object

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37588 entries, 0 to 37587
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37588 non-null  int64
 1   mes                         37588 non-null  int64
 2   ano                         37588 non-null  int64
 3   mes_ano                     37588 non-null  str
 4   aisp                        37588 non-null  int64
 5   risp                        37588 non-null  int64
 6   munic                       37588 non-null  str
 7   mcirc                       37588 non-null  int64
 8   regiao                      37588 non-null  str
 9   hom_doloso                  37588 non-null  int64
 10  lesao_corp_morte            37588 non-null  int64
 11  latrocinio                  37588 non-null  int64
 12  cvli                        37588 non-null  int64
 13  hom_por_interv_policial     37588 non-null  int64
 14  feminicidio                 2466 non-null   float64
 15  letalidade_violenta         37588 non-null  int64
 16  tentat_hom                  37588 non-null  int64
 17  tentativa_feminicidio       2466 non-null   float64
 18  lesao_corp_dolosa           37588 non-null  int64
 19  estupro                     37588 non-null  int64
 20  hom_culposo                 37588 non-null  int64
 21  lesao_corp_culposa          37588 non-null  int64
 22  roubo_transeunte            37588 non-null  int64
 23  roubo_celular               37588 non-null  int64
 24  roubo_em_coletivo           37588 non-null  int64
 25  roubo_rua                   37588 non-null  int64
 26  roubo_veiculo               37588 non-null  int64
 27  roubo_carga                 37588 non-null  int64
 28  roubo_comercio              37588 non-null  int64
 29  roubo_residencia            37588 non-null  int64
 30  roubo_banco                 37588 non-null  int64
 31  roubo_cx_eletronico         37569 non-null  float64
 32  roubo_conducao_saque        37588 non-null  int64
 33  roubo_apos_saque            37588 non-null  int64
 34  roubo_bicicleta             20199 non-null  float64
 35  outros_roubos               37588 non-null  int64
 36  total_roubos                37588 non-null  int64
 37  furto_veiculos              37588 non-null  int64
 38  furto_transeunte            37588 non-null  int64
 39  furto_coletivo              37588 non-null  int64
 40  furto_celular               37588 non-null  int64
 41  furto_bicicleta             20199 non-null  float64
 42  outros_furtos               37588 non-null  int64
 43  total_furtos                37588 non-null  int64
 44  sequestro                   37588 non-null  int64
 45  extorsao                    37588 non-null  int64
 46  sequestro_relampago         37588 non-null  int64
 47  estelionato                 37588 non-null  int64
 48  apreensao_drogas            37588 non-null  int64
 49  posse_drogas                32942 non-null  float64
 50  trafico_drogas              32942 non-null  float64
 51  apreensao_drogas_sem_autor  32942 non-null  float64
 52  recuperacao_veiculos        37588 non-null  int64
 53  apf                         32942 non-null  float64
 54  aaapai                      32942 non-null  float64
 55  cmp                         32942 non-null  float64
 56  cmba                        32942 non-null  float64
 57  ameaca                      37588 non-null  int64
 58  pessoas_desaparecidas       37588 non-null  int64
 59  encontro_cadaver            37588 non-null  int64
 60  encontro_ossada             37588 non-null  int64
 61  pol_militares_mortos_serv   37588 non-null  int64
 62  pol_civis_mortos_serv       37588 non-null  int64
 63  registro_ocorrencias        37588 non-null  int64
 64  fase                        37588 non-null  int64
dtypes: float64(12), int64(50), str(3)
memory usage: 18.6 MB

In [19]:
df.describe()

,cisp,mes,ano,aisp,risp,mcirc,hom_doloso,lesao_corp_morte,latrocinio,cvli,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
count,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,3.758800e+04,37588.000000,37588.000000,37588.000000,37588.000000,...,32942.000000,32942.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000,37588.000000
mean,81.724513,6.453203,2014.274822,20.152708,3.869932,3.791586e+06,2.916383,0.028227,0.095190,3.039800,...,8.737812,0.643737,41.372938,3.231244,0.360434,0.022906,0.013329,0.002208,445.302011,2.989066
std,48.320601,3.465985,6.677154,11.350589,2.011415,1.740552e+06,4.318591,0.180091,0.365578,4.433564,...,14.763082,1.642005,39.454679,4.167554,0.986363,0.180845,0.130521,0.049155,399.884405,0.103996
min,1.000000,1.000000,2003.000000,1.000000,1.000000,3.300100e+06,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,38.000000,3.000000,2009.000000,10.000000,2.000000,3.302601e+06,0.000000,0.000000,0.000000,0.000000,...,2.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,107.000000,3.000000
50%,78.000000,6.000000,2014.000000,20.000000,4.000000,3.304557e+06,1.000000,0.000000,0.000000,1.000000,...,5.000000,0.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,371.000000,3.000000
75%,125.000000,9.000000,2020.000000,30.000000,6.000000,3.304557e+06,4.000000,0.000000,0.000000,4.000000,...,11.000000,1.000000,56.000000,5.000000,0.000000,0.000000,0.000000,0.000000,665.000000,3.000000
max,168.000000,12.000000,2026.000000,43.000000,7.000000,9.999999e+06,43.000000,6.000000,9.000000,43.000000,...,419.000000,60.000000,370.000000,191.000000,112.000000,10.000000,4.000000,2.000000,3185.000000,3.000000

In [20]:
df_furto_celular_cisp = df.groupby('cisp')['roubo_em_coletivo'].sum().reset_index() #reset_index transforma em coluna

df_furto_celular_cisp = df_furto_celular_cisp.sort_values(by='roubo_em_coletivo', ascending=False)

df_furto_celular_cisp

     cisp  roubo_em_coletivo
17     21              12855
52     59              11511
57     64               8761
35     39               7872
25     29               7316
..    ...                ...
118   142                  1
77     92                  0
115   139                  0
129   155                  0
130   156                  0

[138 rows x 2 columns]

In [21]:
df_aaapai_cisp = df.groupby('cisp')['aaapai'].sum().reset_index()

df_aaapai_cisp = df_aaapai_cisp.sort_values(by='aaapai', ascending=False)

df_aaapai_cisp

#ctrl+D para substituir palavras iguais

     cisp  aaapai
104   126  3661.0
8      12  3655.0
10     14  3346.0
65     74  3343.0
12     16  3179.0
..    ...     ...
130   156    18.0
129   155    16.0
131   157    14.0
94    111    13.0
77     92    12.0

[138 rows x 2 columns]

In [22]:
# Usando .loc
df_capital = df.loc[df['munic'] == 'Rio de Janeiro']

# Usando .query() — sintaxe alternativa mais legível
df_capital = df.query("munic == 'Rio de Janeiro'")

# Repetindo o groupby apenas para a capital
df_cisp_capital = df_capital.groupby('cisp')['furto_celular'].sum().reset_index()

df_cisp_capital = df_cisp_capital.sort_values(by='furto_celular', ascending=False)

df_cisp_capital

    cisp  furto_celular
12    16          25709
2      5          24695
10    14          18286
8     12          16929
0      1          15952
5      9          15009
6     10          14571
14    18          14047
1      4          13992
28    32          12623
31    35          12092
15    19           8717
13    17           8491
25    29           8023
38    42           7995
9     13           7532
19    23           7283
11    15           7109
17    21           6932
30    34           6907
33    37           6605
3      6           6526
29    33           6078
18    22           5714
32    36           5555
37    41           5405
16    20           5248
20    24           4673
23    27           4627
24    28           4067
21    25           4005
22    26           4001
40    44           3729
26    30           3726
34    38           3076
35    39           2899
39    43           2833
36    40           2301
27    31           1702
4      7           1578
7     11            402
41    45             73

In [23]:
# df_cisp_capital já foi criado no passo anterior (groupby + reset_index)
array_furto = np.array(df_cisp_capital['furto_celular'])
array_furto

#grande volume de dados trabalhar com numpay

array([25709, 24695, 18286, 16929, 15952, 15009, 14571, 14047, 13992,
       12623, 12092,  8717,  8491,  8023,  7995,  7532,  7283,  7109,
        6932,  6907,  6605,  6526,  6078,  5714,  5555,  5405,  5248,
        4673,  4627,  4067,  4005,  4001,  3729,  3726,  3076,  2899,
        2833,  2301,  1702,  1578,   402,    73])

In [35]:
maximo = np.max(array_furto)
minimo = np.min(array_furto)
media = np.mean(array_furto)
mediana = np.median(array_furto)
q1 = np.percentile(array_furto, 25)
q2 = np.percentile(array_furto, 50)
q3 = np.percentile(array_furto, 75)
distancia = ((media - mediana) / mediana)


print(f'O valor máixmo é {maximo}')
print(f'O valor mínimo é {minimo}')
print(f'A Média é {media:.2f}')
print(f'A Mediana é {mediana}')
print('Q1:', q1)
print('Q2:', q2)
print('Q3:', q3)
print(f'A distância é de: {distancia:.2%}')

O valor máixmo é 25709
O valor mínimo é 73
A Média é 8040.88
A Mediana é 6565.5
Q1: 4002.0
Q2: 6565.5
Q3: 11248.25
A distância é de: 22.47%

In [25]:
# Usando .loc
df_top25 = df_cisp_capital.loc[df_cisp_capital['furto_celular'] > q3]

# Usando .query()
#df_top25 = df_cisp_capital.query('furto_celular > @q3')
print(df_top25)

    cisp  furto_celular
12    16          25709
2      5          24695
10    14          18286
8     12          16929
0      1          15952
5      9          15009
6     10          14571
14    18          14047
1      4          13992
28    32          12623
31    35          12092

In [26]:
# Usando .loc
df_topmenos25 = df_cisp_capital.loc[df_cisp_capital['furto_celular'] < q1]

# Usando .query()
#df_topmenos25 = df_cisp_capital.query('furto_celular < @q3')
print(df_topmenos25)

df_topmenos25 = df_topmenos25.sort_values(by='furto_celular')

df_topmenos25

    cisp  furto_celular
22    26           4001
40    44           3729
26    30           3726
34    38           3076
35    39           2899
39    43           2833
36    40           2301
27    31           1702
4      7           1578
7     11            402
41    45             73

    cisp  furto_celular
41    45             73
7     11            402
4      7           1578
27    31           1702
36    40           2301
39    43           2833
35    39           2899
34    38           3076
26    30           3726
40    44           3729
22    26           4001

In [27]:
df_roubo_veiculo_cisp = df.groupby('cisp')['roubo_veiculo'].sum().reset_index() #reset_index transforma em coluna

df_roubo_veiculo_cisp = df_roubo_veiculo_cisp.sort_values(by='roubo_veiculo', ascending=False)

df_roubo_veiculo_cisp

     cisp  roubo_veiculo
52     59          37511
57     64          32584
35     39          29321
23     27          27710
30     34          27384
..    ...            ...
77     92              8
115   139              7
116   140              7
113   137              6
114   138              2

[138 rows x 2 columns]

In [28]:
array_roubo_veiculo = np.array(df_roubo_veiculo_cisp['roubo_veiculo'])
array_roubo_veiculo

array([37511, 32584, 29321, 27710, 27384, 24731, 20423, 19889, 19687,
       19265, 19195, 18255, 17937, 16579, 16195, 15540, 15139, 14993,
       14768, 14072, 13937, 12750, 12481, 11965, 11896, 10998, 10995,
       10771, 10079,  9153,  9056,  8539,  8523,  8493,  8158,  7808,
        7699,  7370,  7306,  6883,  6438,  5883,  5187,  4688,  4640,
        4133,  4042,  3880,  3685,  3346,  3263,  2973,  2946,  2763,
        2752,  2525,  2205,  2109,  2042,  2018,  1954,  1951,  1937,
        1902,  1490,  1366,  1299,  1275,  1260,  1175,  1060,  1032,
         971,   925,   786,   772,   749,   655,   579,   500,   481,
         447,   440,   407,   345,   333,   321,   313,   313,   312,
         312,   286,   268,   268,   244,   201,   190,   185,   174,
         173,   152,   129,   106,   103,    90,    90,    87,    81,
          65,    64,    64,    59,    58,    49,    48,    47,    43,
          43,    39,    29,    27,    27,    24,    23,    21,    21,
          21,    20,    20,    18,    17,    13,     9,     8,     7,
           7,     6,     2])

In [29]:
maximo = np.max(array_roubo_veiculo)
minimo = np.min(array_roubo_veiculo)
media = np.mean(array_roubo_veiculo)
mediana = np.median(array_roubo_veiculo)
q1 = np.percentile(array_roubo_veiculo, 25)
q2 = np.percentile(array_roubo_veiculo, 50)
q3 = np.percentile(array_roubo_veiculo, 75)


print(f'O valor máixmo é {maximo}')
print(f'O valor mínimo é {minimo}')
print(f'A Média é {media}')
print(f'A Mediana é {mediana}')
print('Q1:', q1)
print('Q2:', q2)
print('Q3:', q3)

O valor máixmo é 37511
O valor mínimo é 2
A Média é 5209.739130434783
A Mediana é 1217.5
Q1: 103.75
Q2: 1217.5
Q3: 8070.5

In [ ]:
df_top25_roubo_veiculo = df_roubo_veiculo_cisp.loc[df_roubo_veiculo_cisp['roubo_veiculo'] > q3]

df_top25_roubo_veiculo

In [48]:
df = pd.read_csv('pedidos_narashop.csv', sep= ';')
df ['valor_total'] = df['valor_unitario'] * df['quantidade']

df

,pedido_id,vendedor,categoria,produto,status_pedido,quantidade,valor_unitario,prazo_entrega_dias,valor_total
0,10001,Rafael Oliveira,Esportes,Raquete de Beach Tennis,Entregue,5,98.01,12,490.05
1,10002,Leandro Reis,Eletrônicos,SSD Externo,Entregue,4,599.89,8,2399.56
2,10003,Flávia Azevedo,Eletrônicos,Notebook,Entregue,5,3774.96,5,18874.80
3,10004,Lucas Ribeiro,Esportes,Garrafa Térmica,Entregue,1,87.67,4,87.67
4,10005,Vinícius Lopes,Eletrônicos,SSD Externo,Entregue,3,439.02,3,1317.06
...,...,...,...,...,...,...,...,...,...
19995,29996,Tatiane Cunha,Esportes,Raquete de Beach Tennis,Entregue,4,178.86,5,715.44
19996,29997,Ana Lima,Casa e Decoração,Tapete Sala,Em trânsito,4,166.27,5,665.08
19997,29998,Patrícia Rocha,Eletrônicos,Tablet,Cancelado,5,1577.65,4,7888.25
19998,29999,Alexandre Lacerda,Esportes,Bermuda Esportiva,Entregue,4,144.59,9,578.36
19999,30000,Thiago Santos,Casa e Decoração,Quadro Decorativo,Em trânsito,3,65.70,18,197.10